# Generated by Django 6.0.1 on 2026-01-13 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_remove_machine_location_subarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('REPAIR', 'Reparatur 🔧'), ('MAINTENANCE', 'Wartung 🛠️'), ('INSPECTION', 'Inspektion 🔍'), ('OTHER', 'Sonstiges 📝')], default='REPAIR', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, related_name='responsible_orders', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortliche'),
        ),
        migrations.AddField(
            model_name='order',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ausführende Techniker'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.order'),
        ),
    ]
