# Generated by Django 6.0.1 on 2026-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_order_type_order_responsible_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('REPAIR', 'Reparatur 🔧'), ('MAINTENANCE', 'Wartung 🛠️'), ('INSPECTION', 'Inspektion 🔍'), ('OTHER', 'Sonstiges 📝')], default='REPAIR', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Neu'), ('PLN', 'Disponiert'), ('INP', 'In Arbeit'), ('PAU', 'Pausiert'), ('DON', 'Reparatur fertig'), ('TRI', 'Probelauf'), ('REV', 'Abnahme'), ('CLO', 'Geschlossen')], default='NEW', max_length=3),
        ),
    ]
