# Generated by Django 6.0.1 on 2026-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_order_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Neu'), ('PLN', 'Disponiert'), ('INP', 'In Arbeit'), ('PAU', 'Pausiert'), ('DONE', 'Reparatur fertig'), ('TRI', 'Probelauf'), ('REV', 'Abnahme'), ('CLO', 'Geschlossen')], default='NEW', max_length=4),
        ),
    ]
